### ISSUE TITLE
Validation module: CSIP17 dependent on whether descriptive metadata files exist or not?

### ISSUE THREAD

**Issue by PhillipAasvangTommerholt** [keeps/commons-ip#157]
The [testCase.xml](https://github.com/DILCISBoard/eark-ip-test-corpus/blob/integration/corpora/csip/metadata/dmdsec/CSIP17/testCase.xml) for CSIP17 has three scenarios:

One scenario where there is no descriptive metadata files in the package and also no dmdSec
One scenario where there is no descriptive metadata files in the package but a dmdSec describing metadata files
One scenario where there is metadata files in the package but no dmdSec

I am not sure that the validator (v.2.3.3) differentiates between these scenarios? Should there be integrity checks between existence of files versus descriptions in dmdSec as suggested in the testCase.xml?

**Comment by carlosjepard** [comment]
Hello Philip!
I have tested and verified the following:

- When no descriptive metadata files or dmdSec exist, the test passes like it should
- When there are no descriptive metadata files but there is a dmdSec, the test fails, and it explains that there are files referenced in the dmdSec but they don't exist in the metadata/descriptive folder, like it should
- When there are descriptive metadata files but no dmdSec referencing them, the validation passes, which is not correct, since it should fail according to the specification (2.0.4).

Note that i already made a pull request in order to fix this #188
