### ISSUE TITLE
Add support for existing checksums to METS

### ISSUE THREAD

**Issue by mrBaas** [keeps/commons-ip#280]
I was hoping by using setChecksum() on the IPFile class, that checksum generation would be skipped when building METS/ZIP.
But after traversing source code that doesn't seem the case?

We're dealing with large volume of data (in the terrabyte range) that is already covered by checksums, so it seems like a waste to have to generate them all over again in the process of creating the SIP.

**Comment by luis100** [comment]
During construction of the SIP we validate the file, ensuring the reported checksum corresponds to the calculated file checksum. I guess that generally you want to disable this check because you are confident the copy and ZIP of the package will work well, or you are open to accept the risk due to the time constraints.

This is not the usual use case, but it should be a easy thing to turn of by setting [this variable](https://github.com/keeps/commons-ip/blob/master/src/main/java/org/roda_project/commons_ip/utils/Utils.java#L184) to be configurable (from environment variable?) and default to `true`.

**Comment by hmiguim** [comment]
A new property was added: skipChecksumCalculation which will skip the checksum validation.  More information can be found in the README.md file.
