### ISSUE TITLE
EARK-SIP with Bagit format

### ISSUE THREAD

**Issue by mhalkiad** [keeps/commons-ip#31]
Hi all,
I am trying to use the library with Bagit format but I have no info/javadoc/documentation about it. Please, is it possible to have more information about that?

I have already created a SIP with correct structure and METS successfully.

Thank you in advance.

Regards.

**Comment by hsilva-keep** [comment]
@mhalkiad, in the README file you can find code sample for creating an E-ARK SIP (METS + custom folder structure). 
If, instead of an E-ARK SIP, you want to create a BagIt SIP you just need to change the first line of the code sample by instantiating BagIt (https://github.com/keeps/commons-ip/blob/master/src/main/java/org/roda_project/commons_ip/model/impl/bagit/BagitSIP.java) instead of EARKSIP.
